### ISSUE TITLE
Inset citation in text

### ISSUE THREAD

**Issue by thorstenwagner** [ONLYOFFICE/plugin-zotero#48] opened 2022-03-24 14:46 UTC
So far I can only add a bibliography. It would be great to have the possibility to add a citation in text.

**Comment by ShockwaveNN** [comment] 2022-03-24 15:42
Duplicate of https://github.com/ONLYOFFICE/plugin-zotero/issues/19

**Closed by ShockwaveNN** 2022-03-24 15:42 UTC
Labels: duplicate
