### ISSUE TITLE
Allow citations in text

### ISSUE THREAD

**Issue by kryptec** [ONLYOFFICE/plugin-zotero#49] opened 2022-04-14 06:52 UTC
Unless I'm doing something wrong, it seems that you can only add an entire bibliography at once with this plugin?

The expected behaviour for this type of program would be to add a citation at the correct point in the text, and then generate a bibliography at the end with all the citations getting their appropriate numbers (or appropriate tag given the reference style). 

So I'm not sure if I'm just not getting something, or asking for an enhancement.

I'm using the desktop version on linux

**Comment by ShockwaveNN** [comment] 2022-04-14 07:02
Sorry, we do not support citations right now

Duplicate of https://github.com/ONLYOFFICE/plugin-zotero/issues/19

**Closed by ShockwaveNN** 2022-04-14 07:02 UTC
